services:
  backend:
    build: ./backend
    container_name: backend
    networks:
      - my-app-network
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    networks:
      - my-app-network
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://backend:8000

networks:
  my-app-network:
    driver: bridge
